### PR TITLE
Ntd1hc/feat/8 prometheus client for python

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Holger,
Hi Thomas,

This PR adds `prometheus-client` as dependency for this package as Issue #8 .

Besides, I also maintained this repository files and workflow for stand-alone and AIO release pipeline:
- Added `.gitignore` for this repository
- Separated version information into `version.py` file: is used by AIO pipeline for Releasing package
- Updated Release workflow

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Ngoan,

unfortunately this has some negative impact:

```
from PrometheusInterface.version import VERSION as LIBRARY_VERSION
from PrometheusInterface.version import VERSION_DATE as LIBRARY_VERSION_DATE
```

Reason: The interface library is imported by the Robot Framework.

In documentation I wrote, this is a way to import the library:

`Library    %{ROBOTPYTHONSITEPACKAGESPATH}/PrometheusInterface/prometheus_interface.py`

in this case `version.py` is searched under `site-packages`. This works, but requires an installation.

I do not like that an installation shall be required. There is no need to do an installation.

Users who are not yet convinced to use this library, have the chance - for first tries - to use the repository local version in this way (without installation):

`Library    ../../../PrometheusInterface/prometheus_interface.py`

But unfortunately in this case `version.py` is searched under `site-packages` also. Without installation this causes an error. This makes no sense.

For sure it might be possible to manipulate the search paths for imports to solve this problem. On the other hand the library is an one-file-tool. And therefore I do not like to add another file to this package - only to store the version number.

The repository configuration is able to access the version number in this way also:

```
from PrometheusInterface.prometheus_interface import LIBRARY_VERSION
from PrometheusInterface.prometheus_interface import LIBRARY_VERSION_DATE
```

And therefore I would say, the build process should be able to do it in the same way.

**Comment by ngoan1608** [comment]
Hi Holger,

The `version.py` file is convention for a job in release AIO pipeline to get the package version and use that info to create corresponding release tag for publishing Pypi and creating Github Release. All our repositories are structured as this except this repository.

The version info can be get as your proposal but it requires the changes from pipeline and tool chains (which is not a python script) to get version from your file without any convention name. Furthermore, any new package which is as one-file-tool likes this will requires again an adaption in pipeline.

I have no idea about one-file-tool or using without installation, but I thought it in the context of single Python package (not only a single file) and a bigger one - Robotframework AIO package.

Anyway, I will add the adaption for AIO release pipeline and rollback the change of `version` if your given idea is really required.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

now I understand your implementation.

Maybe this can be a solution:

https://github.com/test-fullautomation/RobotFramework_AIO/issues/301

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
looks good to me!
Thank you,
 Thomas

**Pull request merged**
